spring:
  datasource:
    #url: jdbc:mysql:db-container/capstone
    url: jdbc:mysql://localhost:3306/capstone # Default, overridden in prod profile
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
        naming-physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging.level:
           root: INFO # Default, overridden in prod profile
           org-springframework:
                           web: INFO
                           jpa: INFO
server:
  port: 8000
  
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,loggers"