spring:
  profiles:
    active: "@spring.profiles.active@" # Allows for external configuration override, e.g., via environment variable
  datasource:
    url: jdbc:mysql://localhost:3306/capstone # Default, overridden in prod profile
    username: root
    password: root1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
        naming-physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: DEBUG # Default, overridden in prod profile

server:
  port: 8000
  
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,loggers"

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://example.com:3306/capstone

logging:
  level:
    root: INFO
